# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the aws-codedeploy-orb
  aws-code-deploy: circleci/aws-code-deploy@1.0
# Orchestrate or schedule a set of jobs
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: jitsi-demo
          bundle-bucket: ddd-deploys
          bundle-key: jitsi-demo
          deployment-group: jitsi-demo
          service-role-arn: arn:aws:iam::432667451394:role/jitsi-demo-codedeploy
